name: Claude Code PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-pr-review:
    if: contains(github.event.pull_request.labels.*.name, 'claude-review') || contains(github.event.comment.body, '@claude-review')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Claude Code
        run: |
          pip install anthropic
          curl -fsSL https://claude.ai/install.sh | sh
          
      - name: Review PR with Claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR details
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          
          # Get diff
          git diff origin/$BASE_BRANCH...HEAD > pr_diff.txt
          
          # Create review prompt
          PROMPT="Please review this pull request for the donkeycar repository:
          
          Title: $PR_TITLE
          Description: $PR_BODY
          
          Context: This is a self-driving car library for Python. Please review for:
          1. Code quality and adherence to project standards in CLAUDE.md
          2. Potential bugs or issues
          3. Performance implications
          4. Testing coverage
          5. Documentation needs
          6. Security considerations
          
          Here's the diff:
          $(cat pr_diff.txt)
          
          Provide constructive feedback and suggestions."
          
          # Run Claude Code review
          echo "$PROMPT" | claude --non-interactive --project-dir . > review_response.txt
          
          # Post review as comment
          gh pr comment $PR_NUMBER --body-file review_response.txt