name: Push docs

on:
  push:
    branches:
      - new_dev
    paths:
      - docs/**
      - .github/workflows/push-docs.yml
      - mkdocs.yml

jobs:
  mkdocs-build-and-push:
    name: mkdocs and push to github
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          auto-activate-base: true
          channels: defaults, conda-forge
      - run: |
          conda info
          conda install mkdocs
          pip install mkdocs-material
          conda list
          mkdocs gh-deploy --force -v
          echo Created docs on github pages