name: Python pip package and test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8'] # can't use 3.9 as this req tf 2.5
      fail-fast: false
    defaults:
      # makes sure github actions environment is set (so test_train is not run)
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Checkout donkeycar
        run: pip install -e .[pc,tf,torch,dev,ci]
      - name: Run tests
        run: pytest


