name: Python package and test

on:
  push:
  pull_request:

jobs:
  checkout-test:
    name: Checkout and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            ENV_FILE: install/envs/mac.yml
          - os: ubuntu-latest
            ENV_FILE: install/envs/ubuntu.yml
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create python 3.9 conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          activate-environment: donkey
          environment-file: ${{matrix.ENV_FILE}}
          auto-activate-base: false
          channels: default, conda-forge, pytorch
          channel-priority: true
      # Workaround for https://github.com/actions/runner-images/issues/6910 / https://github.com/conda/conda/issues/12303
      - name: Downgrade conda
        if: matrix.os == 'ubuntu-latest'
        run: |
          conda config --set allow_conda_downgrades true
          conda install conda=4.12.0 -y
      - name: Conda info and list
        run: |
          echo Environment file ${{matrix.ENV_FILE}}
          conda info
          conda list
      - name: Install donkey
        run: pip install -e .[pc]
      - name: Run tests
        run: pytest
